# Definitng tensors in TensorFlow

In [1]:
import tensorflow as tf

In [2]:
# 0D tensor
d0 =  tf.ones((1,))

In [3]:
# 1D tensor
d1 =  tf.ones((2,))

In [4]:
# 2D tensor
d2 =  tf.ones((2,2))

In [5]:
# 3D tensor
d3 =  tf.ones((2,2,2))

In [6]:
# print the 3D tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


# Defining constants in TensorFlow

In [7]:
from tensorflow import constant

# define 2X3 constant
a = constant(3, shape =[2,3])

In [8]:
print(a)

tf.Tensor(
[[3 3 3]
 [3 3 3]], shape=(2, 3), dtype=int32)


In [10]:
b = constant([1,2,3,4], shape =[2,2])

In [11]:
print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [13]:
c = tf.fill([2,3],7)

In [14]:
print(c)

tf.Tensor(
[[7 7 7]
 [7 7 7]], shape=(2, 3), dtype=int32)


# Defining and initializing variables

In [17]:
# Define a variable

a0 =  tf.Variable([1,2,3,4,5,6], dtype = tf.float32)
a1 =  tf.Variable([1,2,3,4,5,6], dtype = tf.float16)

In [18]:
# define a constant

b = tf.constant(2,tf.float32)

In [19]:
# compute their product

c0 = tf.multiply(a0,b)
c1 = a0*b

In [20]:
print(c0)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


In [21]:
print(c1)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


# Exercise

you will use it to transform a numpy array, credit_numpy, into a tensorflow constant, credit_constant. This array contains feature columns from a dataset on credit card holders.

In [22]:
import pandas as pd
import numpy as np


In [23]:
credit = pd.read_csv('./data/credit.csv')
credit_numpy = credit.to_numpy()
credit.head()

0    1     2        3
0  2.0  1.0  24.0   3913.0
1  2.0  2.0  26.0   2682.0
2  2.0  2.0  34.0  29239.0
3  2.0  1.0  37.0  46990.0
4  2.0  1.0  57.0   8617.0

In [24]:
# Convert the credit_numpy array into  a tensorflow constant
credit_constant = tf.constant(credit_numpy)

# Print constant datatype
print('The datatype is:', credit_constant.dtype)

# Print constant shape
print('The shape is:', credit_constant.shape)

The datatype is: <dtype: 'float64'>
The shape is: (30000, 4)


Unlike a constant, a variable's value can be modified. This will be quite useful when we want to train a model by updating its parameters. Constants can't be used for this purpose, so variables are the natural choice.

Let's try defining and working with a variable.

In [27]:
# Detine the 1-dimensional variable A1
A1 = tf.Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)
# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)


 A1:  <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

 B1:  [1 2 3 4]
