# Basic Operations

In [1]:
import tensorflow as tf


In [2]:
# 0D tendors
A0 = tf.constant([1])
B0 = tf.constant([2])

In [3]:
# 1D tendors
A1 = tf.constant([1,2])
B1 = tf.constant([3,4])

In [5]:
# 2D tendors
A2 = tf.constant([[1,2],[3,4]])
B2 = tf.constant([[5,6],[7,8]])

In [7]:
# add
c0 = tf.add(A0,B0)
c1 = tf.add(A1,B1)
c2 = tf.add(A2,B2)

In [10]:
# multiply
D0 = tf.ones(1)
D31 = tf.ones([3,1])
D34 = tf.ones([3,4])
D43 = tf.ones([4,3])

E0 = tf.multiply(A0,B0)

In [11]:
# vector multiply
E1 = tf.matmul(D34,D43)

In [12]:
# define 2X3X4 of ones

G = tf.ones([2,3,4])

In [13]:
# all dimsensions
H = tf.reduce_sum(G)

In [14]:
# sum over 0,1,2 dimsensions
H0 = tf.reduce_sum(G,0)
H1 = tf.reduce_sum(G,1)
H2 = tf.reduce_sum(G,2)

# Performing element-wise multiplication


In [15]:
# Define tensors A1 and A23 as constants
A1 = tf.constant([1, 2, 3, 4])
A23 = tf.constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = tf.ones_like(A1)
B23 = tf.ones_like(A23)

# Perform element-wise multiplication
C1 = tf.multiply(A1, B1)
C23 = tf.multiply(A23, B23)

# Print the tensors C1 and C23
print('C1: {}'.format(C1.numpy()))
print('C23: {}'.format(C23.numpy()))

C1: [1 2 3 4]
C23: [[1 2 3]
 [1 6 4]]


# Making predictions with matrix multiplication

In [16]:
# Define features, params, and bill as constants
features = tf.constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = tf.constant([[1000], [150]])
bill = tf.constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = tf.matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


# Summing over tensor dimensions

In [17]:
wealth = tf.constant([[11, 50], [7, 2], [4, 60], [3, 0], [25, 10]])
tf.reduce_sum(wealth)

tf.reduce_sum(wealth, 1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([61,  9, 64,  3, 35])>